article: https://www.hackster.io/jakub-smejkal/smart-and-secure-wifi-router-with-hardwario-iot-kit-44fc5e
video: https://www.youtube.com/watch?v=5fihG2xp4y8
articles:
  - title: Wireless QR Code for Guest WiFi
    url: https://www.hackster.io/154412/wireless-qr-code-for-guest-wifi-6f7159
    description: Are you tired of placing notes with passwords around your company building and replacing them every time you change password?
    images:
      - url: https://hackster.imgix.net/uploads/attachments/1050369/_BEC0JYcZSN.blob?auto=compress%2Cformat&w=900&h=675&fit=min
  - title: Wireless QR Code for Guest WiFi
    url: https://www.hackster.io/jakub-smejkal/smart-and-secure-wifi-router-with-hardwario-iot-kit-44fc5e
    description: Make your own smart router with Turris MOX and HARDWARIO IoT Kit. You can make it change the password periodicaly and show it as a QR code.
    images:
      - url: https://hackster.imgix.net/uploads/attachments/1050333/_8PsfZmJVIq.blob?auto=compress%2Cformat&w=900&h=675&fit=min
images:
  - title:
    url: https://cdn.myshoptet.com/usr/shop.hardwario.com/user/shop/category_portrait/174-1_project-thermostat-lcd-a-4.jpg?5de56e1c
assembly:
  - name: BigClown Climate Module
  - name: BigClown Core Module
  - name: BigClown Mini Battery Module
